
deploy: build
	cp -r dist/* ..

build:
	yarn build

clean:
	rm -rf dist/ tmp/ artifacts/

clean_root:
	rm -rf ../*.html ../*.js ../*.txt ../*.json ../*.css ../404/ ../about/ \
		../blog/ ../contact/ ../donations/  ../team/ ../static/ ../templates/ \
        ../timeline/ ../welcome/